from __future__ import annotations

from pathlib import Path

from .officex_exec.anchor_extractor import (
    build_officex_live_anchor_snapshot,
    render_officex_live_anchor_snapshot_markdown,
)
from .models import (
    OfficeXAnchorPrepReport,
    OfficeXManualReviewInput,
    OfficeXReviewLedger,
    OfficeXReviewLedgerFinding,
)
from .runtime_common import (
    ensure_mutable_candidate,
    load_runtime_structured_model,
    resolve_runtime_artifact_dir,
    write_runtime_json,
    write_runtime_markdown,
)


def load_manual_review_input(path: Path) -> OfficeXManualReviewInput:
    return load_runtime_structured_model(path, OfficeXManualReviewInput)


def load_review_ledger(path: Path) -> OfficeXReviewLedger:
    return load_runtime_structured_model(path, OfficeXReviewLedger)


def _default_review_ledger_path(review_input_path: Path, review_id: str) -> Path:
    stem = review_input_path.stem
    return review_input_path.parent / f"{stem}.{review_id}.review_ledger.json"


def render_review_ledger_markdown(ledger: OfficeXReviewLedger, review_ledger_path: Path) -> str:
    lines = [
        "# OfficeX Review Ledger",
        "",
        f"- Review ID: `{ledger.review_id}`",
        f"- Target document ID: `{ledger.target_document_id}`",
        f"- Generated by: `{ledger.generated_by}`",
        f"- Findings: {len(ledger.findings)}",
        f"- Output path: `{review_ledger_path}`",
    ]
    if ledger.findings:
        lines.extend(["", "## Findings", ""])
        for finding in ledger.findings:
            lines.append(
                "- "
                f"`{finding.issue_id}` / `{finding.issue_kind}` / `{finding.severity}` / "
                f"`{finding.status}` / rule `{finding.anchor_rule.anchor_rule_type}`"
            )
    return "\n".join(lines)


def build_review_ledger(
    *,
    review_input_path: Path,
    output_path: Path | None = None,
) -> tuple[OfficeXReviewLedger, Path]:
    resolved_input_path = review_input_path.expanduser().resolve()
    review_input = load_manual_review_input(resolved_input_path)
    ledger = OfficeXReviewLedger(
        review_id=review_input.review_id,
        target_document_id=review_input.target_document_id,
        generated_by=review_input.generated_by,
        findings=[
            OfficeXReviewLedgerFinding(
                issue_id=finding.issue_id,
                title=finding.title,
                issue_kind=finding.issue_kind,
                severity=finding.severity,
                status=finding.status,
                review_comment=finding.review_comment,
                anchor_rule=finding.anchor_rule,
            )
            for finding in review_input.findings
        ],
    )
    resolved_output_path = (
        output_path.expanduser().resolve()
        if output_path is not None
        else _default_review_ledger_path(resolved_input_path, review_input.review_id)
    )
    resolved_output_path.parent.mkdir(parents=True, exist_ok=True)
    write_runtime_json(resolved_output_path, ledger.model_dump(mode="json"))
    write_runtime_markdown(
        resolved_output_path.with_suffix(".md"),
        render_review_ledger_markdown(ledger, resolved_output_path),
    )
    return ledger, resolved_output_path


def render_officex_anchor_snapshot_markdown(
    ledger: OfficeXReviewLedger,
    review_ledger_path: Path,
    snapshot,
    findings: list[str],
) -> str:
    lines = [
        "# OfficeX Live Anchor Snapshot",
        "",
        f"- Review ID: `{ledger.review_id}`",
        f"- Review ledger: `{review_ledger_path}`",
        f"- Candidate path: `{snapshot.candidate_path}`",
        f"- Candidate hash: `{snapshot.candidate_hash}`",
        f"- Target issues: {', '.join(snapshot.target_issue_ids)}",
        f"- Anchor count: {len(snapshot.anchors)}",
        f"- Findings: {len(findings)}",
        "",
        "## Anchors",
        "",
    ]
    for anchor in snapshot.anchors:
        lines.extend(
            [
                f"- `{anchor.anchor_id}`",
                f"  issue `{anchor.issue_id}` / role `{anchor.anchor_role}` / kind `{anchor.block_kind}` / status `{anchor.uniqueness_status}`",
                f"  location `{anchor.location_hint}` / excerpt `{anchor.text_excerpt or '[none]'}`",
            ]
        )
    lines.extend(["", "## Findings", ""])
    if findings:
        for finding in findings:
            lines.append(f"- {finding}")
    else:
        lines.append("- All requested anchors resolved uniquely.")
    return "\n".join(lines)


def extract_anchors_from_review_ledger(
    *,
    candidate_path: Path,
    review_ledger_path: Path,
    output_dir: Path | None = None,
) -> OfficeXAnchorPrepReport:
    resolved_candidate = ensure_mutable_candidate(candidate_path, action="inspect")
    resolved_review_ledger_path = review_ledger_path.expanduser().resolve()
    if not resolved_candidate.exists():
        raise FileNotFoundError(f"File not found: {resolved_candidate}")
    if resolved_candidate.suffix.lower() != ".docx":
        raise ValueError(f"Candidate must be a .docx file: {resolved_candidate}")

    ledger = load_review_ledger(resolved_review_ledger_path)
    rules = [finding.anchor_rule for finding in ledger.findings]
    snapshot, findings = build_officex_live_anchor_snapshot(
        resolved_candidate,
        resolved_review_ledger_path,
        [finding.issue_id for finding in ledger.findings],
        rules,
    )
    artifact_dir = resolve_runtime_artifact_dir(
        resolved_candidate,
        runtime_subdir="review_prep",
        artifact_id=ledger.review_id,
        hidden_dir_name=".officex_review_prep",
        output_dir=output_dir,
    )
    snapshot_path = artifact_dir / "live_anchor_snapshot.json"
    snapshot_markdown_path = artifact_dir / "live_anchor_snapshot.md"
    write_runtime_json(snapshot_path, snapshot.model_dump(mode="json"))
    write_runtime_markdown(
        snapshot_markdown_path,
        render_officex_live_anchor_snapshot_markdown(snapshot, findings),
    )
    return OfficeXAnchorPrepReport(
        review_id=ledger.review_id,
        target_document_id=ledger.target_document_id,
        candidate_path=resolved_candidate,
        review_ledger_path=resolved_review_ledger_path,
        output_dir=artifact_dir,
        anchor_snapshot_path=snapshot_path,
        anchor_snapshot_markdown_path=snapshot_markdown_path,
        issue_count=len(ledger.findings),
        anchor_count=len(snapshot.anchors),
        finding_count=len(findings),
    )
